build:
  verbosity: detailed

install:
  - cmake --version

build_script:
  - mkdir build
  - cd build
  - cmake .. 
  - make lab1_double_base_palindrome_tests
  - tests/lab1test/lab1_double_base_palindrome_tests
  - make lab2_array_2d_step1_tests
  - tests/lab2test/lab2_array_2d_step1_tests
