image:
- Visual Studio 2015

platform:
- x64

environment:
  matrix:
  - arch: Win64

build:
  verbosity: detailed

install:
  - cmake --version

build_script:
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - mkdir build
  - cd build
  - cmake .. -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER="C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1"
  - mingw64-make lab1_double_base_palindrome_tests
  - tests/lab1test/lab1_double_base_palindrome_tests 
