sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc

install:
  - echo `which $CC`
  - echo `which $CXX`
  - curl https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr

script:
  - echo `which $CXX`
  - mkdir build && cd build;
    cmake -DCMAKE_CXX_COMPILER=$CXX
  - make make lab1_double_base_palindrome_tests

notifications:
  email: false
